require 'csv'
# BD - METODOS DE ALTERACAO E INCLUSAO DE DADOS E INSTANCIAMENTO DO ARQUIVO CSV
class Cookbook
  # RECEBE O CAMINHO DO CSV COMO PARAMETRO
  def initialize(csv_file_path)
    # SALVANDO EM UMA VARIAVEL O CAMINHO
    @csv_file = csv_file_path
    # DECLARACAO DA ARRAY QUE GUARADARA AS INSTANCIAS DE RECIPE
    @recipes = []
    # CHAMADA DO METODO PARA REALIZAR O LOAD DO CSV E GUARDAR AS INFORMACOES JA EXISTENTES NA ARRAY DE REPICES
    load_csv
  end

  # METODO PARA ADICIONAR RECIPE NA ARRAY, E CHAMADO NO CONTROLLER, REPONSAVEL PELO ENVIO DA INSTACIA DE RECIPE
  def add_recipe(recipe)
    @recipes << recipe
    # APOS ADICIONAR A RECIPE NA ARRAY E CHAMADO O METODO SAVE_CSV PARA SALVAR(ATUALIZAR) O ARQUIVO CSV
    save_csv
  end

  # RETONAR A ARRAY DE RECIPES PARA O CONTROLLER, QUE POR SUA VEZ ENVIARA PARA VIEW REALIZAR A IMPRESSAO
  def all
    @recipes
  end

  # METODO PARA REMOVER RECIPE, RECEBE O INDEX COLETADO PELA VIEW
  def remove_recipe(index_rm)
    @recipes.delete_at(index_rm)
    # APOS REMOCAO E' SOBRESCRITO AS INFORMACOES DO ARQUIVO CSV COM O METODO SAVE_CSV
    save_csv
  end

  # METODO PARA SALVAR/ALTERAR AS INFORMACOES NO ARQUIVO CSV
  def save_csv
    # ABERTURA DO ARQUIVO E ITERACAO DAS LINHAS DO CSV, RECEBE O CAMINHO DO ARQUIVO
    CSV.open(@csv_file, 'wb') do |csv|
      # ITERACAO SOBRE A ARRAY DE RECIPES
      @recipes.each do |recipe|
        # CHAMADA DOS METODOS NAME E DESCRIPTION DA CLASSE RECIPE PARA SALVAR AS INFORMACAO NO CSV
        csv << [recipe.name, recipe.description]
      end
    end
  end

  # CARREGAMENTO DO ARQUIVO CSV PARA SALVAR AS INFORMACAO EM RUBY PARA SEREM PROCESSADAS.
  # O LOAD E' REALIZADO APENAS UMA VEZ, LOGO APOS O INSTANCIAMENTO DO OBJETO DA CLASSE COOKBOOK
  def load_csv
    # RECEBE O CAMINHO DO ARQUIVO. A ITERACAO E' FEITA PELAS LINHAS, QUE SAO ARRAYS DE STRINGS
    CSV.foreach(@csv_file) do |row|
      # SALVAR O INDEX [0] QUE E' O NOME
      name = row[0]
      # SALVAR O INDEX [1] QUE E' A DESCRICAO
      description = row[1]
      # EM CADA ITERACAO, APOS SALVAR OS VALORES DE NAME E DESCRIPTION, E' INSTANCIADO O OBJETO RECIPE E SALVO
      # NA ARRAY @RECIPES
      recipe = Recipe.new(name, description)
      @recipes << recipe
    end
  end
end
